name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to main

jobs:
  sync-to-hf-space:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout the GitHub repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Verify HF token is set (safe, no logging of actual token)
      - name: Check HF token
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "HF_TOKEN is not set!"
            exit 1
          else
            echo "HF_TOKEN is set ✅"
          fi
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      # 3️⃣ Push repo to Hugging Face Space
      - name: Push to HF Space
        run: |
          git config --global user.email "afzalking0001@gmail.com"
          git config --global user.name "Afzal-04"

          # Remove remote if exists
          git remote remove hf || echo "Remote removed"

          # Add HF Space remote using token
          git remote add hf https://$HF_TOKEN@huggingface.co/spaces/Afzal-04/AgriLeafNet

          # Fetch remote to avoid branch errors
          git fetch hf || echo "No remote branch yet"

          # Switch/create main branch
          git checkout -B main

          # Add all files and commit if changes exist
          git add .
          git commit -m "Sync from GitHub" || echo "No changes to commit"

          # Push forcefully to HF Space
          git push -u hf main --force
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
