name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  sync-to-hf-space:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # 3️⃣ Install huggingface_hub
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub==0.16.4

      # 4️⃣ Verify HF token
      - name: Check HF token
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "HF_TOKEN not set!"
            exit 1
          fi
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      # 5️⃣ Sync files to existing Space
      - name: Push to Hugging Face Space
        run: |
          mkdir -p hf_sync
          cp app.py requirements.txt potato_leaf_disease_cnn_model.keras hf_sync/
          cd hf_sync
          huggingface-cli login --token $HF_TOKEN
          git init
          git remote add origin https://huggingface.co/spaces/Afzal-04/AgriLeafNet
          git add .
          git commit -m "Sync from GitHub"
          git push -u origin main --force
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
