name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  sync-to-hf-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check HF token
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "HF_TOKEN is not set!"
            exit 1
          else
            echo "HF_TOKEN is set ✅"
          fi
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Prepare files for HF Space
        run: |
          mkdir hf_push
          cp app.py hf_push/
          cp requirements.txt hf_push/
          cp potato_leaf_disease_cnn_model.keras hf_push/

      - name: Push to Hugging Face Space
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: Afzal-04/AgriLeafNet
          repo_type: space
          hf_token: ${{ secrets.HF_TOKEN }}
