name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to main

jobs:
  sync-to-hf-space:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout your GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Verify HF token is set
      - name: Check HF token
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "HF_TOKEN is not set!"
            exit 1
          else
            echo "HF_TOKEN is set ✅"
          fi
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      # 3️⃣ Push files to Hugging Face Space
      - name: Push to HF Space
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: Afzal-04/AgriLeafNet
          repo_type: space
          hf_token: ${{ secrets.HF_TOKEN }}
