name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  sync-to-hf-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Push to Hugging Face Space
        run: |
          git config --global user.email "afzalking0001@gmail.com"
          git config --global user.name "Afzal-04"

          git remote remove hf || echo "Remote removed"
          git remote add hf https://$HF_TOKEN@huggingface.co/spaces/Afzal-04/Agrileafnet

          git fetch hf || echo "No remote branch yet"
          git checkout -B main
          git add .
          git commit -m "Sync from GitHub" || echo "No changes to commit"
          git push -u hf main --force
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
